pipeline {

    agent any

    options {
        skipDefaultCheckout(true)
    }

    // =========================================================
    // TOOLS
    // =========================================================

    tools {
        jdk 'Java21'
        maven 'Maven'
    }

    // =========================================================
    // ENVIRONMENT
    // =========================================================

    environment {

        // Application directory
        APP_DIR = 'Bank-App-CI-main/Bank-CI-main'

        // SonarQube
        SONAR_PROJECT_KEY = 'gcbank'
        SONAR_PROJECT_NAME = 'gcbank'
        SONARQUBE_CREDENTIALS = credentials('sonarqube-token')
    }

    // =========================================================
    // STAGES
    // =========================================================

    stages {

        // =====================================================
        // 1. CLEAN WORKSPACE
        // =====================================================

        stage('Clean Workspace') {
            steps {
                cleanWs()
            }
        }

        // =====================================================
        // 2. GIT CHECKOUT
        // =====================================================

        stage('Git Checkout') {
            steps {

                echo "=========================================="
                echo "GIT CHECKOUT"
                echo "=========================================="

                git(
                    branch: 'main',
                    credentialsId: 'git-token',
                    url: 'https://github.com/Ragav-s-web/BANKING-APPLICATIONS.git'
                )

                echo "Git checkout completed."
            }
        }

        // =====================================================
        // 3. CHECK JAVA AND MAVEN
        // =====================================================

        stage('Check Java & Maven') {
            steps {

                sh '''
                    echo "=========================================="
                    echo "JAVA VERSION"
                    echo "=========================================="

                    java -version

                    echo ""
                    echo "=========================================="
                    echo "JAVAC VERSION"
                    echo "=========================================="

                    javac -version

                    echo ""
                    echo "=========================================="
                    echo "JAVA HOME"
                    echo "=========================================="

                    echo "$JAVA_HOME"

                    echo ""
                    echo "=========================================="
                    echo "MAVEN VERSION"
                    echo "=========================================="

                    mvn -version
                '''
            }
        }

        // =====================================================
        // 4. MAVEN CLEAN
        // =====================================================

        stage('Maven Clean') {
            steps {

                dir("${APP_DIR}") {

                    sh '''
                        echo "=========================================="
                        echo "MAVEN CLEAN"
                        echo "=========================================="

                        mvn clean
                    '''
                }
            }
        }

        // =====================================================
        // 5. COMPILE
        // =====================================================

        stage('Compile') {
            steps {

                dir("${APP_DIR}") {

                    sh '''
                        echo "=========================================="
                        echo "MAVEN COMPILE"
                        echo "=========================================="

                        mvn compile
                    '''
                }
            }
        }

        // =====================================================
        // 6. UNIT TEST
        // =====================================================

        stage('Test') {
            steps {

                dir("${APP_DIR}") {

                    sh '''
                        echo "=========================================="
                        echo "UNIT TEST"
                        echo "=========================================="

                        mvn test
                    '''
                }
            }
        }

        // =====================================================
        // 7. SONARQUBE ANALYSIS
        // =====================================================

        
        stage('Package') {

            steps {

                dir("${APP_DIR}") {

                    sh '''
                        echo "=========================================="
                        echo "CREATING JAR"
                        echo "=========================================="

                        mvn package -DskipTests
                    '''
                }
            }
        }

        // =====================================================
        // 10. SHOW BUILD ARTIFACT
        // =====================================================

        stage('Show Artifact') {

            steps {

                dir("${APP_DIR}") {

                    sh '''
                        echo "=========================================="
                        echo "BUILD ARTIFACT"
                        echo "=========================================="

                        ls -lh target/

                        echo ""
                        echo "JAR FILES:"
                        find target -maxdepth 1 -type f -name "*.jar" -ls
                    '''
                }
            }
        }

        // =====================================================
        // 11. DOCKER CHECK
        // =====================================================

        stage('Docker Check') {

            steps {

                sh '''
                    echo "=========================================="
                    echo "DOCKER CHECK"
                    echo "=========================================="

                    docker --version

                    echo ""
                    echo "Docker information:"
                    docker info
                '''
            }
        }

        // =====================================================
        // 12. DOCKER BUILD
        // =====================================================

        stage('Docker Build') {

            steps {

                dir("${APP_DIR}") {
			
			sh 'docker build -t ragavapp .'
        // =====================================================
        // 13. DOCKER IMAGE CHECK
        // =====================================================
				}
        stage('Docker Image Check') {

            steps {
		
		sh 'docker tag ragavapp ragavkumar/ragavapp:latest'
            }
        }

        // =====================================================
        // 14. DOCKER LOGIN
        // =====================================================

        stage('Docker Login') {

            steps {

                withCredentials([
                    usernamePassword(
                        credentialsId: 'docker-cred',
                        usernameVariable: 'DOCKER_USERNAME',
                        passwordVariable: 'DOCKER_PASSWORD'
                    )
                ]) {

                    sh '''

                        echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
    
                        docker push ragavkumar/ragavapp:latest
                    '''
                }
            }
        }

        stage('Docker Logout') {

            steps {

                sh '''
                    echo "=========================================="
                    echo "DOCKER LOGOUT"
                    echo "=========================================="

                    docker logout || true

                    echo "Docker logout completed."
                '''
            }
        }
    }

    // =========================================================
    // POST ACTIONS
    // =========================================================

    post {

        success {

            echo '''
            ==========================================
              BANKING APPLICATION PIPELINE SUCCESS
            ==========================================
            '''

            echo "Application build completed successfully."
            echo "Build Number : ${BUILD_NUMBER}"
            echo "Docker Image : ${DOCKER_IMAGE}:${IMAGE_TAG}"
        }

        failure {

            echo '''
            ==========================================
              BANKING APPLICATION PIPELINE FAILED
            ==========================================
            '''

            echo "Build Number : ${BUILD_NUMBER}"
            echo "Check the Jenkins Console Output."
        }

        always {

            echo "=========================================="
            echo "BUILD INFORMATION"
            echo "=========================================="

            echo "BUILD NUMBER : ${BUILD_NUMBER}"
            echo "BUILD STATUS : ${currentBuild.currentResult}"
        }
    }
}
