pipeline {

    agent any

    tools {
        jdk 'Java21'
        maven 'Maven'
    }

    environment {
        APP_DIR = 'Bank-App-CI-main/Bank-CI-main'

        SONAR_PROJECT_KEY = 'gcbank'
        SONAR_PROJECT_NAME = 'gcbank'

        DOCKER_IMAGE = 'castromeka/gcbank'
        IMAGE_TAG = "v${BUILD_NUMBER}"
    }

    stages {

        // =========================================================
        // 1. CLEAN WORKSPACE
        // =========================================================

        stage('Clean Workspace') {
            steps {
                cleanWs()
            }
        }


        // =========================================================
        // 2. GIT CHECKOUT
        // =========================================================

        stage('Git Checkout') {
            steps {
                git branch: 'main',
                    credentialsId: 'git-token',
                    url: 'https://github.com/Ragav-s-web/BANKING-APPLICATIONS.git'
            }
        }


        // =========================================================
        // 3. CHECK JAVA & MAVEN
        // =========================================================

        stage('Check Java & Maven') {
            steps {
                sh '''
                    echo "=========================================="
                    echo "JAVA VERSION"
                    echo "=========================================="

                    java -version

                    echo ""
                    echo "JAVAC VERSION"
                    javac -version

                    echo ""
                    echo "JAVA HOME"
                    echo $JAVA_HOME

                    echo ""
                    echo "=========================================="
                    echo "MAVEN VERSION"
                    echo "=========================================="

                    mvn -version
                '''
            }
        }


        // =========================================================
        // 4. CLEAN
        // =========================================================

        stage('Clean') {
            steps {
                dir("${APP_DIR}") {
                    sh '''
                        mvn clean
                    '''
                }
            }
        }


        // =========================================================
        // 5. COMPILE
        // =========================================================

        stage('Compile') {
            steps {
                dir("${APP_DIR}") {
                    sh '''
                        mvn compile
                    '''
                }
            }
        }


        // =========================================================
        // 6. TEST
        // =========================================================

        stage('Test') {
            steps {
                dir("${APP_DIR}") {
                    sh '''
                        mvn test
                    '''
                }
            }
        }


        // =========================================================
        // 7. SONARQUBE ANALYSIS
        // =========================================================

        stage('SonarQube Analysis') {
            steps {

                dir("${APP_DIR}") {

                    withSonarQubeEnv('sonar') {

                        sh '''
                            mvn org.sonarsource.scanner.maven:sonar-maven-plugin:sonar \
                            -Dsonar.projectKey=${SONAR_PROJECT_KEY} \
                            -Dsonar.projectName=${SONAR_PROJECT_NAME} \
                            -Dsonar.java.binaries=target/classes
                        '''
                    }
                }
            }
        }


        // =========================================================
        // 8. QUALITY GATE
        // =========================================================

        stage('Quality Gate') {
            steps {

                timeout(time: 5, unit: 'MINUTES') {

                    waitForQualityGate(
                        abortPipeline: false
                    )
                }
            }
        }


        // =========================================================
        // 9. PACKAGE
        // =========================================================

        stage('Package') {
            steps {

                dir("${APP_DIR}") {

                    sh '''
                        mvn package -DskipTests
                    '''
                }
            }
        }


        // =========================================================
        // 10. DOCKER BUILD
        // =========================================================

        stage('Docker Build') {
            steps {

                dir("${APP_DIR}") {

                    sh '''
                        docker build \
                        -t ${DOCKER_IMAGE}:${IMAGE_TAG} .
                    '''
                }
            }
        }


        // =========================================================
        // 11. DOCKER LOGIN & PUSH
        // =========================================================

        stage('Docker Push') {
            steps {

                script {

                    withDockerRegistry(
                        credentialsId: 'docker-cred'
                    ) {

                        sh '''
                            docker push ${DOCKER_IMAGE}:${IMAGE_TAG}
                        '''
                    }
                }
            }
        }
    }


    // =============================================================
    // POST ACTIONS
    // =============================================================

    post {

        success {

            echo '''
            ==========================================
              BANKING APPLICATION PIPELINE SUCCESS
            ==========================================
            '''

            echo "Docker Image:"
            echo "${DOCKER_IMAGE}:${IMAGE_TAG}"
        }

        failure {

            echo '''
            ==========================================
              BANKING APPLICATION PIPELINE FAILED
            ==========================================
            '''

            echo "Please check the Jenkins Console Output."
        }

        always {

            echo "=========================================="
            echo "BUILD NUMBER : ${BUILD_NUMBER}"
            echo "BUILD STATUS : ${currentBuild.currentResult}"
            echo "=========================================="
        }
    }
}
